jobs:
- name: hello_world_job
  plan:
  - task: hello_world_task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: ubuntu }
      run:
        path: sh
        args:
        - -exc
        - |
          whoami
          date
          echo "Hello World"
