resources:
- name: app_sources
  type: git
  source:
    uri: https://github.com/justmejus/jhipsterForCFLocal
- name: staging_deployment
  type: cf
  source:
    api: https://api.local.pcfdev.io 
    username: user
    password: pass
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true

jobs:
- name: simple-deploy
  plan:
  - get: app_sources
    trigger: true
  - task: build
    config:
      platform: linux
      inputs:
      - name: app_sources
      outputs:
      - name: jhi4local_jar
      image_resource:
        type: docker-image
        source: { repository: java, tag: 8-jdk }
      run:
        path: sh
        args:
        - -exc
        - |
          export TERM=dumb
          cd app_sources
          ./mvnw package -DskipTests
          mv target/jhipster-for-cf-local-0.0.1-SNAPSHOT.war ../jhi4local_jar
  - put: staging_deployment
    params:
      manifest: app_sources/manifest.yml
